version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=naro
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/config:/etc/mysql/conf.d"
volumes:
  mysql:
